#!/bin/sh /etc/rc.common
START=99

run_autoupdate()
{
	local enable
	config_get_bool enable $1 enable
	local forceupdate
	config_get_bool forceupdate $1 forceupdate
	if [ $enable = 1 ]; then
		local minute
		local hour
		config_get week $1 week
		config_get minute $1 minute
		config_get hour $1 hour
		[ $minute = 0 ] && minute="00"
		[ $week = 7 ] && week="*"
		sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
		/etc/init.d/cron restart
		if [ $forceupdate = 1 ];then
			echo "$minute $hour * * $week bash /bin/AutoUpdate.sh -f" >> /etc/crontabs/root
		else
			echo "$minute $hour * * $week bash /bin/AutoUpdate.sh" >> /etc/crontabs/root
		fi
		echo "已重启 AutoUpdate 服务."
	else
		sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
		/etc/init.d/cron restart
		echo "已重启 AutoUpdate 服务."
	fi
}

start()
{
	config_load autoupdate
	config_foreach run_autoupdate login
}

stop()
{
	echo "已停止 AutoUpdate 服务."
}
