#!/bin/sh /etc/rc.common
START=99

run_autoupdate()
{
	local enable
	config_get_bool enable $1 enable
	if [ $enable = 1 ]; then
		local minute
		local hour
		config_get week $1 week
		config_get minute $1 minute
		config_get hour $1 hour
		if [ $minute == 0 ] ; then
			minute="00"
		fi
		if [ $week == 7 ] ; then
			week="*"
		fi
		sed -i '/AutoUpdate/d' /etc/crontabs/root >/dev/null 2>&1
		/etc/init.d/cron restart
		echo "$minute $hour * * $week sleep 3 && bash /bin/AutoUpdate.sh" >> /etc/crontabs/root
		echo "已开启 自动更新 服务."
	else
		sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
		/etc/init.d/cron restart
		echo "已开启 自动更新 服务."
	fi
}

start()
{
	config_load autoupdate
	config_foreach run_autoupdate login
}

stop()
{
	echo "已关闭 自动更新 服务."
}
